config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"
  get "/about", to: 'pages#about'

  resources :artworks, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  has_attachment :photo

  SIZE = ['11 X 14', '18 X 24', '44 X 44', '20 X 26', '24 X 48'].sort
  MEDIUM = Artwork.select(:medium).map(&:medium).sort.uniq!

  validates :title, presence: true
  validates :medium, presence: true
  validates :category, :inclusion => { :in => SIZE }
  validates :price, presence: true

  def next
    self.class.where("id > ?", id).first
  end

  def previous
    self.class.where("id < ?", id).last
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  def index
    @q = Artwork.ransack(params[:q])
    @artworks = @q.result(distinct: true).order(created_at: :desc)
  end

  def show
    @artwork = Artwork.find(params[:id])
  end

  def artwork_params
    params.require(:artwork).permit(:title, :photo, :category, :medium, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @last_five = Artwork.last(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artworks/index.html.erb
<div id="artwork-banner" class="header-name">
  <h2>artworks</h2>
  <div class="container form-group">
    <%= search_form_for @q do |f|%>
      <div class="row">
        <div class="col-md-3 col-md-offset-3">
          <%= f.label :category_matches, 'Size' %>
          <%= f.select :category_matches, options_for_select(Artwork::SIZE), {class:"dropdown-item ", include_blank: true}, class: "btn btn-default dropdown-toggle form-control" %>
        </div>
        <div class="col-md-3 no-gutters">
          <%= f.label :category_matches, 'Medium' %>
          <%= f.select :medium_matches, options_for_select(Artwork::MEDIUM), {include_blank: true}, class: "btn btn-default dropdown-toggle form-control" %>
        </div>
      </div>
      <br>
        <div class="row form-inline">
          <div class="col-md-2 col-md-offset-3">
            <div class="input-group">
              <span class="input-group-addon">$</span>
              <%= f.search_field :price_gteq, class:"form-control" %>
            </div>
          </div>
          <h5 class="col-md-1" style="text-align: center;">to</h5>
          <div class="col-md-2">
            <div class="input-group">
              <span class="input-group-addon">$</span>
              <%= f.search_field :price_lteq, class:"form-control" %>
            </div>
          </div>
          <%= f.submit "Filter", class:"btn btn-default col-sm-1" %>
        </div>
    <% end %>
  </div>
</div>
<div class="index-content container">
  <% if @artworks.length > 0 %>
    <% @artworks.each_slice(2) do |artworks| %>
      <div class="index-row col-sm-6 col-xs-12">
        <% artworks.each do |artwork| %>
          <%= render partial: 'shared/artwork', locals: { artwork: artwork, height: "500px"  }%>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <h3><br>I am always working on new artwork, check back soon. <br> <%= link_to 'Click here to see all my artworks', artworks_path %></h3>
  <% end %>
</div>

app/views/artworks/show.html.erb
  <div class="container" id="show-container">
  <div class="previous-indicator indicator hidden-sm hidden-xs ">
    <% unless @artwork.id == Artwork.last.id %>
      <%= link_to "<i class='fa fa-circle' aria-hidden='true'></i>".html_safe, @artwork.next %>
      <% unless @artwork.id == (Artwork.last.id + 1) %>
        <%= link_to "<i class='fa fa-circle' aria-hidden='true'></i>".html_safe, @artwork.next.next %>
      <% end %>
    <% end %>
  </div>
  <div class="image">
    <% if @artwork.vertical == true %>
      <%= cl_image_tag @artwork.photo.path%>
    <% else %>
      <%= cl_image_tag @artwork.photo.path%>
    <% end %>
  </div>
  <div class="next-indicator indicator hidden-sm hidden-xs">
    <% unless @artwork.id == Artwork.first.id %>
      <%= link_to "<i class='fa fa-circle' aria-hidden='true'></i>".html_safe, @artwork.previous %>
      <% unless @artwork.id == (Artwork.first.id - 1) %>
        <%= link_to "<i class='fa fa-circle' aria-hidden='true'></i>".html_safe, @artwork.previous.previous %>
      <% end %>
    <% end %>
  </div>
  <div class="show-content container row">
    <h4 class="col-md-3 d-block-sm" id="price">$<%= @artwork.price %></h4>
    <h4 class="col-md-3 d-block-sm offset-md-3" ><%=@artwork.title %></h4>
    <h4 class="col-md-3 d-block-sm offset-md-6" id="description"><%= @artwork.medium %></h4>
    <h4 class="col-md-3 d-block-sm offest-md-9" id="category"><%= @artwork.category %></h4>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-117599066-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-117599066-1');
    </script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag(source='favicon.ico')%>
    <title>S.K. Hammond Art</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
      <%= render "shared/navbar"%>
      <%= javascript_include_tag 'application' %>
      <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div id="col-img">
    <%= image_tag "Studio-inside.jpg" %>
    <h1>S. K. Hammond</h1>
  </div>
  <br>
  <div id="bio">
    <br>
      <h3 id="quote">
      "It is good to love many things, for therein lies the true strength, and whosoever loves much, performs much, and can accomplish much, and what is done in love is well done." -Vincent Van Gogh
      </h3>

    <h2>Bio</h2>
    <p>
      <br>
      What do you see?
      <br>
      "What do I see" is the question I ask myself when I create my watercolor painting of " rocks" and abstracts. Either imagination takes over, and I see shapes of people, animals, trees and all sorts of beautiful organic objects or the shapes just come alive and meld together with the paint to form clusters of chaos and color. I feel successful in a painting when I am in awe of it and spend a long time looking at it to see what mixed feelings it has to offer me.
      <br>
      I hope you enjoy what you see in the paintings and you discover a smile coming upon your face.
    </p>
  </div>
  <div id="studio">
    <h2>Studio</h2>
    <br>
    <div id="studio-images" >
      <div id="col-img-1" class="col-sm-4 col-xs-6">
        <%= image_tag "Studio-front.jpg" %>
      </div>
      <div id="col-img-2" class="col-sm-4 col-xs-6">
        <%= image_tag "Studio-door.jpg" %>
      </div>
      <div id="col-img-3" class="col-sm-4 col-xs-6">
        <%= image_tag "Studio-hearts.jpg" %>
      </div>
    </div>
  </div>
  <div id=map>
    <div id="map-content" class="col-xs-12 col-md-6">
      <h3>Located at:</h3>
      <p>308 Prince St., B100 <br> 55101 Saint Paul, Minnesota <br></p>
    </div>
    <div class="col-xs-12 col-md-6">
      <a href="https://www.google.com/maps/dir//308+Prince+St.,+B100+55101+Saint+Paul,+Minnesota/"><img src="https://maps.googleapis.com/maps/api/staticmap?center=308+Prince+St.,+B100+55101+Saint+Paul,+Minnesota&zoom=16&scale=1&size= 800x300&maptype=roadmap&format=png&visual_refresh=true&markers=size:mid%7Ccolor:0x959595%7Clabel:%7C308+Prince+St.,+B100+55101+Saint+Paul,+Minnesota" alt="Google Map of 308 Prince St., B100 55101 Saint Paul, Minnesota"></a>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div id="front-content">
  <div class="hidden-sm hidden-xs">
    <%= link_to about_path do %>
      <div id="front-box" class="col-md-6 col-xs-12">
          <h1>S.K.Hammond Art</h1>
          <h3><i class="fa fa-arrow-left" aria-hidden="true"></i> Bio</h3>
      </div>
    <% end %>
  </div>
    <div id="front-artwork" class="col-md-6 col-xs-12 carousel slide no-gutters" data-ride="carousel" data-interval="2500">
      <h2 class="hidden-md hidden-lg hidden-xl">S.K.Hammond Art</h2>
      <div class="carousel-inner">
        <div class="item active">
          <%= cl_image_tag @last_five[0].photo.path, class:"d-block w-100", :width=>0.40, :crop => :fill %>
        </div>
        <div class="item">
          <%= cl_image_tag @last_five[1].photo.path, class:"d-block w-100", :width=>0.40, :crop => :fill  %>
        </div>
        <div class="item">
          <%= cl_image_tag @last_five[2].photo.path, class:"d-block w-100", :width=>0.40, :crop => :fill  %>
        </div>
        <div class="item">
          <%= cl_image_tag @last_five[3].photo.path, class:"d-block w-100", :width=>0.40, :crop => :fill  %>
        </div>
        <div class="item">
          <%= cl_image_tag @last_five[4].photo.path, class:"d-block w-100", :width=>0.40, :crop => :fill  %>
        </div>
      </div>
    <%= link_to artworks_path do %>
      <div id="front-box-overlay">
        <h3>Artwork <i class="fa fa-arrow-right" aria-hidden="true"></i></h3>
      </div>
    <% end %>
    </div>
</div>

app/views/shared/_artwork.html.erb
<%= link_to artwork_path(artwork) do %>
  <div class="card" style="display: inline-block; height: <%= height %>;">
    <div class="card-img" id="img" style="background-image: url('<%= cl_image_path( artwork.photo.path, {height: 400, width: 400,crop: :fit})%>')">
    </div>
    <div class="card-background">
      <h2><%= artwork.title %></h2>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <div class="navbar-wagon-item hidden-sm hidden-xs">
    <div class="dropdown">
      <i class="fa fa-caret-down dropdown-toggle" data-toggle="dropdown">  S.K. Hammond Art</i>
      <ul class="dropdown-menu dropdown-menu-left navbar-wagon-dropdown-menu">
        <li><%= link_to 'artist', about_path %></li>
        <li><%= link_to 'artwork', artworks_path %></li>
        <li><%= link_to 'home', root_path %></li>
      </ul>
    </div>
  </div>
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-left navbar-wagon-dropdown-menu">
        <li><%= link_to 'artist', about_path %></li>
        <li><%= link_to 'artwork', artworks_path %></li>
        <li><%= link_to 'home', root_path %></li>
      </ul>
    </div>
  </div>

  <div class="navbar-wagon-item right-navbar hidden-sm">
    <%= link_to 'https://www.facebook.com/skhammondartist/', target: :_blank do %>
      <i class="fa fa-facebook-square" aria-hidden="true"></i>
    <% end %>
    <%= link_to 'https://www.instagram.com/suekhammond/', target: :_blank do %>
      <i class="fa fa-instagram" aria-hidden="true"></i>
    <% end %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<nav id="sidebar">
    <!-- Sidebar Links -->
    <ul class="list-unstyled components">
        <li class="active">
            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">
                <i class="glyphicon glyphicon-home"></i>
                Home
            </a>
        </li>
        <li>
            <a href="#">
                <i class="glyphicon glyphicon-briefcase"></i>
                About
            </a>
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">
                <i class="glyphicon glyphicon-duplicate"></i>
                Pages
            </a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
                <li><a href="#">Page 1</a></li>
                <li><a href="#">Page 2</a></li>
                <li><a href="#">Page 3</a></li>
            </ul>
        </li>
        <li>
            <a href="#">
                <i class="glyphicon glyphicon-link"></i>
                Portfolio
            </a>
        </li>
        <li>
            <a href="#">
                <i class="glyphicon glyphicon-send"></i>
                Contact
            </a>
        </li>
    </ul>
</nav>